import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const source=fs.readFileSync(path.join(root,'src/index.template.html'),'utf8');
const config=JSON.parse(fs.readFileSync(path.join(root,'app.config.json'),'utf8'));
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const deps=JSON.parse(fs.readFileSync(path.join(root,'dependencies.json'),'utf8'));

test('v1.1.0 adds a canvas-first mobile workspace without changing desktop markup',()=>{
  assert.equal(config.version,'1.1.3');
  assert.equal(pkg.version,'1.1.3');
  assert.match(source,/PDF Pipeline Builder <span class="version-badge">v1\.1\.3<\/span>/);
  assert.match(source,/class="mobile-action-bar"/);
  assert.match(source,/id="mobileAddButton"/);
  assert.match(source,/id="mobileRunButton"/);
  assert.match(source,/mobile-sheet-palette/);
  assert.match(source,/mobile-sheet-inspector/);
  assert.match(source,/mobile-sheet-tools/);
  assert.match(source,/id="mobileToolsSheet"/);
  assert.match(source,/id="mobileExpandButton"/);
  assert.match(source,/class="mobile-sheet-done"[^>]*data-i18n="mobileDone">完了<\/button>/);
  assert.match(source,/mobileDone:'Done'/);
  assert.match(source,/nodeActions:'ノード操作'/);
  assert.match(source,/renderPreviewSection\(root,node\);const actionSection=/);
  assert.match(source,/\.mobile-sheet-title\{[^}]*white-space:nowrap/);
  assert.match(source,/\.mobile-sheet-close\{position:absolute;right:9px;top:12px/);
  assert.doesNotMatch(source,/<div class="mobile-sheet-head"><span aria-hidden="true"><\/span>/);
  assert.match(source,/body\.mobile-sheet-tools \.mobile-tools-sheet/);
  assert.doesNotMatch(source,/body\.mobile-sheet-tools \.workspace-toolbar/);
  assert.match(source,/mobile-sheet-result/);
  assert.match(source,/function openMobileSheet\(name\)/);
  assert.match(source,/openMobileSheet\('inspector'\)/);
  assert.match(source,/if\(isMobileLayout\(\)\)openMobileSheet\('result'\)/);
  assert.match(source,/@media\(max-width:760px\)/);
  assert.match(source,/grid-template-columns:repeat\(5,minmax\(0,1fr\)\)/);
  assert.match(source,/connect-src 'none'/);
  assert.match(source,/introTitle:'PDF処理をつないで組み立てる'/);
  assert.doesNotMatch(source,/PDF処理を、つないで組み立てる/);
  assert.match(source,/PDF処理をノードで組み、途中結果を確認しながら実行できます。/);
});

test('mobile sheets remain dismissible and the primary action exposes generated results',()=>{
  assert.match(source,/id="mobileSheetBackdrop"/);
  assert.match(source,/data-mobile-sheet-close/);
  assert.match(source,/mobileSheetBackdrop'\)\.onclick=closeMobileSheets/);
  assert.match(source,/e\.key==='Escape'.*mobile-sheet-open/);
  assert.match(source,/if\(outputBytes\)\{openMobileSheet\('result'\)/);
  assert.match(source,/function setExpanded\(expanded\)\{[^}]*closeMobileSheets\(\)/);
  assert.match(source,/mobileExpandButton'\)\.onclick=\(\)=>setExpanded/);
  assert.match(source,/canvasElement\.addEventListener\('pointerdown',[\s\S]*?,true\);/);
  assert.match(source,/canvasElement\.addEventListener\('pointerup',[\s\S]*?,true\);/);
  assert.match(source,/\.nec-port,\.nec-node-toolbar/);
  assert.match(source,/M5 4v8a7 7 0 0 0 14 0V4/);
  assert.match(source,/M7 7v4M10 7v2\.5M13 7v4M16 7v2\.5/);
  assert.match(source,/\.workspace-toolbar\{display:none!important\}/);
  assert.match(source,/mobileResult:'結果'/);
  assert.match(source,/mobileResult:'Result'/);
  assert.match(source,/id="previewDialogCanvas"/);
  assert.match(source,/id="outputPreviewCanvas"/);
  assert.match(source,/renderPdfBytesToCanvas/);
  assert.match(source,/StandaloneAssets\.importModule\('pdfjs','main'\)/);
  assert.doesNotMatch(source,/id="previewDialogFrame"/);
  assert.doesNotMatch(source,/id="outputPreviewFrame"/);
  const pdfjs=deps.dependencies.find(item=>item.id==='pdfjs');
  assert.equal(pdfjs?.version,'6.2.108');
  assert.equal(pdfjs?.package,'pdfjs-dist');
  const pdfLib=deps.dependencies.find(item=>item.id==='pdf-lib');
  assert.equal(pdfLib?.assets?.find(asset=>asset.key==='runtime')?.compression,'auto');
});
